name: Vulnerability Scan Workflow

# Trigger the action on push and pull request events and schedule
on:
  push:
    branches:
      - main  # You can specify which branch you want to trigger the action on (e.g., 'main')
  schedule:
    - cron: '0 0 * * *'  # This cron expression triggers the action every night at 12 AM UTC

jobs:
  scan:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    permissions:
      contents: read
      security-events: write
      issues: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up URLs
        id: setup_urls
        run: echo "urls=${{ secrets.TARGET_URL }}" >> $GITHUB_ENV

      - name: Debug URLs
        run: echo ${{ env.urls }}

      - name: ZAP Scan
        run: |
          for url in $(echo ${{ env.urls }} | tr "," "\n")
          do
            echo "Scanning $url"
            zaproxy/action-full-scan@v0.12.0 --target "$url"
          done
