name: Vulnerability Scan Workflow

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      issues: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Login to Application
        run: |
          curl -c cookies.txt -d "username=admin&password=admin" ${{ secrets.TARGET_URL }}/login.jsp

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: '${{ secrets.TARGET_URL }}/'
          contextFile: '.zap/context.xml'
          authLoginUrl: '${{ secrets.TARGET_URL }}/login.jsp'
          authUsername: 'admin'
          authPassword: 'admin'
          authLoginIndicator: 'Logout'

